console.log("Hello World!");
let a = 10;
console.log(a);
a = "a is string";
console.log(a);
const c = "Vasya";
console.log(c);
// c = "petya";
console.log(a + "  " + c);
a = 7777;
let s = `строка шаблонная a=${a}`;
console.log(s);
a = 3.14;
console.log(`a=${a}`);
console.log(10/0);
console.log(10/"qqq");
console.log(2+2);
console.log("2"+2);
console.log("2"-2);
